<?php
/* ME MIMEI 1.16.0/1.17.0: nomes do cardápio em inglês e espanhol (id do lanche do cardápio público → [nome, grupo, sabor, porção]). 1.17.0: Refrigerante (Soda/Refresco) e Energético (Energy drink/Bebida energética). */
return [
  162 => ['en' => ['Coca-Cola can', 'Soda', 'Coca-Cola can', 'can 350 ml'], 'es' => ['Coca-Cola lata', 'Refresco', 'Coca-Cola lata', 'lata 350 ml']],
  210 => ['en' => ['Coca-Cola Zero can', 'Soda', 'Coca-Cola Zero can', 'can 350 ml'], 'es' => ['Coca-Cola Zero lata', 'Refresco', 'Coca-Cola Zero lata', 'lata 350 ml']],
  211 => ['en' => ['Coca-Cola 600 ml', 'Soda', 'Coca-Cola 600 ml', 'bottle 600 ml'], 'es' => ['Coca-Cola 600 ml', 'Refresco', 'Coca-Cola 600 ml', 'botella 600 ml']],
  163 => ['en' => ['Coca-Cola 1 L bottle', 'Soda', 'Coca-Cola 1 L bottle', '1 liter'], 'es' => ['Coca-Cola botella 1 L', 'Refresco', 'Coca-Cola botella 1 L', '1 litro']],
  164 => ['en' => ['Coca-Cola 2 L bottle', 'Soda', 'Coca-Cola 2 L bottle', '2 liters'], 'es' => ['Coca-Cola botella 2 L', 'Refresco', 'Coca-Cola botella 2 L', '2 litros']],
  212 => ['en' => ['Guaraná Antarctica can', 'Soda', 'Guaraná Antarctica can', 'can 350 ml'], 'es' => ['Guaraná Antarctica lata', 'Refresco', 'Guaraná Antarctica lata', 'lata 350 ml']],
  213 => ['en' => ['Guaraná Antarctica Zero can', 'Soda', 'Guaraná Antarctica Zero can', 'can 350 ml'], 'es' => ['Guaraná Antarctica Zero lata', 'Refresco', 'Guaraná Antarctica Zero lata', 'lata 350 ml']],
  214 => ['en' => ['Fanta Orange can', 'Soda', 'Fanta Orange can', 'can 350 ml'], 'es' => ['Fanta Naranja lata', 'Refresco', 'Fanta Naranja lata', 'lata 350 ml']],
  215 => ['en' => ['Fanta Orange Zero can', 'Soda', 'Fanta Orange Zero can', 'can 350 ml'], 'es' => ['Fanta Naranja Zero lata', 'Refresco', 'Fanta Naranja Zero lata', 'lata 350 ml']],
  216 => ['en' => ['Sprite can', 'Soda', 'Sprite can', 'can 350 ml'], 'es' => ['Sprite lata', 'Refresco', 'Sprite lata', 'lata 350 ml']],
  217 => ['en' => ['Sprite Zero can', 'Soda', 'Sprite Zero can', 'can 350 ml'], 'es' => ['Sprite Zero lata', 'Refresco', 'Sprite Zero lata', 'lata 350 ml']],
  218 => ['en' => ['Pepsi can', 'Soda', 'Pepsi can', 'can 350 ml'], 'es' => ['Pepsi lata', 'Refresco', 'Pepsi lata', 'lata 350 ml']],
  219 => ['en' => ['Pepsi Black can', 'Soda', 'Pepsi Black can', 'can 350 ml'], 'es' => ['Pepsi Black lata', 'Refresco', 'Pepsi Black lata', 'lata 350 ml']],
  220 => ['en' => ['Soda Limonada (lemon) can', 'Soda', 'Soda Limonada (lemon) can', 'can 350 ml'], 'es' => ['Soda Limonada lata', 'Refresco', 'Soda Limonada lata', 'lata 350 ml']],
  221 => ['en' => ['Soda Limonada Zero can', 'Soda', 'Soda Limonada Zero can', 'can 350 ml'], 'es' => ['Soda Limonada Zero lata', 'Refresco', 'Soda Limonada Zero lata', 'lata 350 ml']],
  222 => ['en' => ['Kuat can', 'Soda', 'Kuat can', 'can 350 ml'], 'es' => ['Kuat lata', 'Refresco', 'Kuat lata', 'lata 350 ml']],
  223 => ['en' => ['Kuat Zero can', 'Soda', 'Kuat Zero can', 'can 350 ml'], 'es' => ['Kuat Zero lata', 'Refresco', 'Kuat Zero lata', 'lata 350 ml']],
  224 => ['en' => ['Schweppes Citrus can', 'Soda', 'Schweppes Citrus can', 'can 350 ml'], 'es' => ['Schweppes Citrus lata', 'Refresco', 'Schweppes Citrus lata', 'lata 350 ml']],
  225 => ['en' => ['Schweppes Citrus Zero can', 'Soda', 'Schweppes Citrus Zero can', 'can 350 ml'], 'es' => ['Schweppes Citrus Zero lata', 'Refresco', 'Schweppes Citrus Zero lata', 'lata 350 ml']],
  226 => ['en' => ['Red Bull 250 ml', 'Energy drink', 'Red Bull 250 ml', 'can 250 ml'], 'es' => ['Red Bull 250 ml', 'Bebida energética', 'Red Bull 250 ml', 'lata 250 ml']],
  227 => ['en' => ['Red Bull Sugarfree 250 ml', 'Energy drink', 'Red Bull Sugarfree 250 ml', 'can 250 ml'], 'es' => ['Red Bull Sugarfree 250 ml', 'Bebida energética', 'Red Bull Sugarfree 250 ml', 'lata 250 ml']],
  228 => ['en' => ['Red Bull 473 ml', 'Energy drink', 'Red Bull 473 ml', 'can 473 ml'], 'es' => ['Red Bull 473 ml', 'Bebida energética', 'Red Bull 473 ml', 'lata 473 ml']],
  229 => ['en' => ['Monster 473 ml', 'Energy drink', 'Monster 473 ml', 'can 473 ml'], 'es' => ['Monster 473 ml', 'Bebida energética', 'Monster 473 ml', 'lata 473 ml']],
  230 => ['en' => ['Monster Ultra 473 ml', 'Energy drink', 'Monster Ultra 473 ml', 'can 473 ml'], 'es' => ['Monster Ultra 473 ml', 'Bebida energética', 'Monster Ultra 473 ml', 'lata 473 ml']],
  231 => ['en' => ['TNT 269 ml', 'Energy drink', 'TNT 269 ml', 'can 269 ml'], 'es' => ['TNT 269 ml', 'Bebida energética', 'TNT 269 ml', 'lata 269 ml']],
  232 => ['en' => ['TNT Zero 269 ml', 'Energy drink', 'TNT Zero 269 ml', 'can 269 ml'], 'es' => ['TNT Zero 269 ml', 'Bebida energética', 'TNT Zero 269 ml', 'lata 269 ml']],
  233 => ['en' => ['Baly 473 ml', 'Energy drink', 'Baly 473 ml', 'can 473 ml'], 'es' => ['Baly 473 ml', 'Bebida energética', 'Baly 473 ml', 'lata 473 ml']],
  234 => ['en' => ['Baly Zero 473 ml', 'Energy drink', 'Baly Zero 473 ml', 'can 473 ml'], 'es' => ['Baly Zero 473 ml', 'Bebida energética', 'Baly Zero 473 ml', 'lata 473 ml']],
  235 => ['en' => ['Fusion 250 ml', 'Energy drink', 'Fusion 250 ml', 'can 250 ml'], 'es' => ['Fusion 250 ml', 'Bebida energética', 'Fusion 250 ml', 'lata 250 ml']],
  17 => ['en' => ['Coxinha', 'Coxinha', 'Classic', '1 medium piece'], 'es' => ['Coxinha', 'Coxinha', 'Tradicional', '1 unidad mediana']],
  198 => ['en' => ['Chicken coxinha', 'Coxinha', 'Chicken', '1 piece'], 'es' => ['Coxinha de pollo', 'Coxinha', 'Pollo', '1 unidad']],
  199 => ['en' => ['Cheese coxinha', 'Coxinha', 'Cheese', '1 piece'], 'es' => ['Coxinha de queso', 'Coxinha', 'Queso', '1 unidad']],
  200 => ['en' => ['Jerky coxinha', 'Coxinha', 'Jerky', '1 piece'], 'es' => ['Coxinha de tasajo', 'Coxinha', 'Tasajo', '1 unidad']],
  18 => ['en' => ['Pastel (fried pie)', null, 'Pastel (fried pie)', '1 street-fair pastel'], 'es' => ['Pastel frito', null, 'Pastel frito', '1 pastel de feria']],
  19 => ['en' => ['Cake', 'Cake', 'Classic', '1 slice'], 'es' => ['Bizcocho', 'Bizcocho', 'Tradicional', '1 rebanada']],
  20 => ['en' => ['Pie', null, 'Pie', '1 slice'], 'es' => ['Tarta', null, 'Tarta', '1 rebanada']],
  21 => ['en' => ['Ruffles', 'Snacks', 'Ruffles', 'bag 45 g'], 'es' => ['Ruffles', 'Snacks', 'Ruffles', 'bolsa 45 g']],
  22 => ['en' => ['Cheetos', 'Snacks', 'Cheetos', 'bag 45 g'], 'es' => ['Cheetos', 'Snacks', 'Cheetos', 'bolsa 45 g']],
  23 => ['en' => ['Doritos', 'Snacks', 'Doritos', 'bag 45 g'], 'es' => ['Doritos', 'Snacks', 'Doritos', 'bolsa 45 g']],
  24 => ['en' => ['Acarajé', null, 'Acarajé', '1 piece'], 'es' => ['Acarajé', null, 'Acarajé', '1 unidad']],
  25 => ['en' => ['Tapioca', 'Tapioca', 'Classic', '1 filled tapioca'], 'es' => ['Tapioca', 'Tapioca', 'Tradicional', '1 tapioca rellena']],
  132 => ['en' => ['Coconut & condensed milk tapioca', 'Tapioca', 'Coconut & condensed milk', '1 tapioca'], 'es' => ['Tapioca de coco y leche condensada', 'Tapioca', 'Coco y leche condensada', '1 tapioca']],
  133 => ['en' => ['Sun-dried beef & cheese tapioca', 'Tapioca', 'Sun-dried beef & cheese', '1 tapioca'], 'es' => ['Tapioca de carne seca y queso', 'Tapioca', 'Carne seca y queso', '1 tapioca']],
  134 => ['en' => ['Guava paste & cheese tapioca', 'Tapioca', 'Guava paste & cheese', '1 tapioca'], 'es' => ['Tapioca de guayaba y queso', 'Tapioca', 'Guayaba y queso', '1 tapioca']],
  135 => ['en' => ['Cream cheese tapioca', 'Tapioca', 'Cream cheese', '1 tapioca'], 'es' => ['Tapioca de queso crema', 'Tapioca', 'Queso crema', '1 tapioca']],
  136 => ['en' => ['Turkey & cheese tapioca', 'Tapioca', 'Turkey & cheese', '1 tapioca'], 'es' => ['Tapioca de pavo y queso', 'Tapioca', 'Pavo y queso', '1 tapioca']],
  137 => ['en' => ['Shrimp tapioca', 'Tapioca', 'Shrimp', '1 tapioca'], 'es' => ['Tapioca de camarón', 'Tapioca', 'Camarón', '1 tapioca']],
  138 => ['en' => ['Sun-dried beef & cream tapioca', 'Tapioca', 'Sun-dried beef & cream', '1 tapioca'], 'es' => ['Tapioca de carne seca y nata', 'Tapioca', 'Carne seca y nata', '1 tapioca']],
  114 => ['en' => ['Coconut tapioca', 'Tapioca', 'Coconut', '1 tapioca'], 'es' => ['Tapioca de coco', 'Tapioca', 'Coco', '1 tapioca']],
  115 => ['en' => ['Grilled cheese tapioca', 'Tapioca', 'Grilled cheese', '1 tapioca'], 'es' => ['Tapioca de queso asado', 'Tapioca', 'Queso asado', '1 tapioca']],
  116 => ['en' => ['Butter tapioca', 'Tapioca', 'Butter', '1 tapioca'], 'es' => ['Tapioca de mantequilla', 'Tapioca', 'Mantequilla', '1 tapioca']],
  118 => ['en' => ['Cheese & coconut tapioca', 'Tapioca', 'Cheese & coconut', '1 tapioca'], 'es' => ['Tapioca de queso y coco', 'Tapioca', 'Queso y coco', '1 tapioca']],
  120 => ['en' => ['Jerky tapioca', 'Tapioca', 'Jerky', '1 tapioca'], 'es' => ['Tapioca de tasajo', 'Tapioca', 'Tasajo', '1 tapioca']],
  121 => ['en' => ['Chicken & cream cheese tapioca', 'Tapioca', 'Chicken & cream cheese', '1 tapioca'], 'es' => ['Tapioca de pollo y queso crema', 'Tapioca', 'Pollo y queso crema', '1 tapioca']],
  122 => ['en' => ['Ham & cheese tapioca', 'Tapioca', 'Ham & cheese', '1 tapioca'], 'es' => ['Tapioca de jamón y queso', 'Tapioca', 'Jamón y queso', '1 tapioca']],
  123 => ['en' => ['Egg tapioca', 'Tapioca', 'Egg', '1 tapioca with 1 egg'], 'es' => ['Tapioca de huevo', 'Tapioca', 'Huevo', '1 tapioca con 1 huevo']],
  124 => ['en' => ['Sausage & cheese tapioca', 'Tapioca', 'Sausage & cheese', '1 tapioca'], 'es' => ['Tapioca de chorizo y queso', 'Tapioca', 'Chorizo y queso', '1 tapioca']],
  125 => ['en' => ['Ground beef tapioca', 'Tapioca', 'Ground beef', '1 tapioca'], 'es' => ['Tapioca de carne molida', 'Tapioca', 'Carne molida', '1 tapioca']],
  126 => ['en' => ['Tuna tapioca', 'Tapioca', 'Tuna', '1 tapioca'], 'es' => ['Tapioca de atún', 'Tapioca', 'Atún', '1 tapioca']],
  127 => ['en' => ['Bacon & cheese tapioca', 'Tapioca', 'Bacon & cheese', '1 tapioca'], 'es' => ['Tapioca de tocino y queso', 'Tapioca', 'Tocino y queso', '1 tapioca']],
  128 => ['en' => ['Banana & cinnamon tapioca', 'Tapioca', 'Banana & cinnamon', '1 tapioca'], 'es' => ['Tapioca de plátano y canela', 'Tapioca', 'Plátano y canela', '1 tapioca']],
  129 => ['en' => ['Chocolate tapioca', 'Tapioca', 'Chocolate', '1 tapioca'], 'es' => ['Tapioca de chocolate', 'Tapioca', 'Chocolate', '1 tapioca']],
  130 => ['en' => ['Nutella & strawberry tapioca', 'Tapioca', 'Nutella & strawberry', '1 tapioca'], 'es' => ['Tapioca de nutella y fresa', 'Tapioca', 'Nutella y fresa', '1 tapioca']],
  131 => ['en' => ['Dulce de leche tapioca', 'Tapioca', 'Dulce de leche', '1 tapioca'], 'es' => ['Tapioca de dulce de leche', 'Tapioca', 'Dulce de leche', '1 tapioca']],
  26 => ['en' => ['Beer (Can)', 'Beer', 'Can', '1 can 350 ml'], 'es' => ['Cerveza Lata', 'Cerveza', 'Lata', '1 lata 350 ml']],
  32 => ['en' => ['Beer (Bottle)', 'Beer', 'Bottle', '1 bottle 355 ml'], 'es' => ['Cerveza Botellín', 'Cerveza', 'Botellín', '1 botella 355 ml']],
  33 => ['en' => ['Beer (600 ml)', 'Beer', '600 ml', '1 bottle 600 ml'], 'es' => ['Cerveza 600 ml', 'Cerveza', '600 ml', '1 botella 600 ml']],
  165 => ['en' => ['Orange juice', 'Juice', 'Orange', '1 glass 300 ml'], 'es' => ['Jugo de naranja', 'Jugo', 'Naranja', '1 vaso 300 ml']],
  166 => ['en' => ['Passion fruit juice', 'Juice', 'Passion fruit', '1 glass 300 ml'], 'es' => ['Jugo de maracuyá', 'Jugo', 'Maracuyá', '1 vaso 300 ml']],
  167 => ['en' => ['Cashew fruit juice', 'Juice', 'Cashew fruit', '1 glass 300 ml'], 'es' => ['Jugo de marañón', 'Jugo', 'Marañón', '1 vaso 300 ml']],
  168 => ['en' => ['Acerola juice', 'Juice', 'Acerola', '1 glass 300 ml'], 'es' => ['Jugo de acerola', 'Jugo', 'Acerola', '1 vaso 300 ml']],
  169 => ['en' => ['Hog plum juice', 'Juice', 'Hog plum', '1 glass 300 ml'], 'es' => ['Jugo de jobo', 'Jugo', 'Jobo', '1 vaso 300 ml']],
  170 => ['en' => ['Umbu juice', 'Juice', 'Umbu', '1 glass 300 ml'], 'es' => ['Jugo de umbú', 'Jugo', 'Umbú', '1 vaso 300 ml']],
  171 => ['en' => ['Red mombin juice', 'Juice', 'Red mombin', '1 glass 300 ml'], 'es' => ['Jugo de ciruela', 'Jugo', 'Ciruela', '1 vaso 300 ml']],
  172 => ['en' => ['Soursop juice', 'Juice', 'Soursop', '1 glass 300 ml'], 'es' => ['Jugo de guanábana', 'Jugo', 'Guanábana', '1 vaso 300 ml']],
  173 => ['en' => ['Guava juice', 'Juice', 'Guava', '1 glass 300 ml'], 'es' => ['Jugo de guayaba', 'Jugo', 'Guayaba', '1 vaso 300 ml']],
  174 => ['en' => ['Mango juice', 'Juice', 'Mango', '1 glass 300 ml'], 'es' => ['Jugo de mango', 'Jugo', 'Mango', '1 vaso 300 ml']],
  175 => ['en' => ['Pineapple juice', 'Juice', 'Pineapple', '1 glass 300 ml'], 'es' => ['Jugo de piña', 'Jugo', 'Piña', '1 vaso 300 ml']],
  176 => ['en' => ['Cupuaçu juice', 'Juice', 'Cupuaçu', '1 glass 300 ml'], 'es' => ['Jugo de cupuazú', 'Jugo', 'Cupuazú', '1 vaso 300 ml']],
  177 => ['en' => ['Tamarind juice', 'Juice', 'Tamarind', '1 glass 300 ml'], 'es' => ['Jugo de tamarindo', 'Jugo', 'Tamarindo', '1 vaso 300 ml']],
  178 => ['en' => ['Lime juice', 'Juice', 'Lime', '1 glass 300 ml'], 'es' => ['Jugo de limón', 'Jugo', 'Limón', '1 vaso 300 ml']],
  179 => ['en' => ['Grape juice', 'Juice', 'Grape', '1 glass 300 ml'], 'es' => ['Jugo de uva', 'Jugo', 'Uva', '1 vaso 300 ml']],
  27 => ['en' => ['Pizza', null, 'Pizza', '1 slice'], 'es' => ['Pizza', null, 'Pizza', '1 rebanada']],
  36 => ['en' => ['Sushi', null, 'Sushi', '8-piece combo'], 'es' => ['Sushi', null, 'Sushi', 'combo de 8 piezas']],
  28 => ['en' => ['Burger', null, 'Burger', '1 sandwich'], 'es' => ['Hamburguesa', null, 'Hamburguesa', '1 sándwich']],
  29 => ['en' => ['Brigadeiro', null, 'Brigadeiro', '1 piece'], 'es' => ['Brigadeiro', null, 'Brigadeiro', '1 unidad']],
  30 => ['en' => ['Ice cream', null, 'Ice cream', '1 scoop'], 'es' => ['Helado', null, 'Helado', '1 bola']],
  31 => ['en' => ['Açaí bowl', null, 'Açaí bowl', 'bowl 500 ml'], 'es' => ['Açaí', null, 'Açaí', 'tazón 500 ml']],
  38 => ['en' => ['Abará', null, 'Abará', '1 piece'], 'es' => ['Abará', null, 'Abará', '1 unidad']],
  39 => ['en' => ['Butter couscous', 'Couscous', 'Butter', '1 slice 150 g'], 'es' => ['Cuscús de mantequilla', 'Cuscús', 'Mantequilla', '1 rebanada 150 g']],
  78 => ['en' => ['Jerky couscous', 'Couscous', 'Jerky', '1 plate 200 g'], 'es' => ['Cuscús de tasajo', 'Cuscús', 'Tasajo', '1 plato 200 g']],
  79 => ['en' => ['Egg couscous', 'Couscous', 'Egg', '1 plate with 1 fried egg'], 'es' => ['Cuscús de huevo', 'Cuscús', 'Huevo', '1 plato con 1 huevo frito']],
  80 => ['en' => ['Scrambled eggs couscous', 'Couscous', 'Scrambled eggs', '1 plate with 2 eggs'], 'es' => ['Cuscús de huevos revueltos', 'Cuscús', 'Huevos revueltos', '1 plato con 2 huevos']],
  81 => ['en' => ['Sausage couscous', 'Couscous', 'Sausage', '1 plate 200 g'], 'es' => ['Cuscús de longaniza', 'Cuscús', 'Longaniza', '1 plato 200 g']],
  82 => ['en' => ['Sardines couscous', 'Couscous', 'Sardines', '1 plate 200 g'], 'es' => ['Cuscús de sardinas', 'Cuscús', 'Sardinas', '1 plato 200 g']],
  83 => ['en' => ['Grilled cheese couscous', 'Couscous', 'Grilled cheese', '1 plate 200 g'], 'es' => ['Cuscús de queso asado', 'Cuscús', 'Queso asado', '1 plato 200 g']],
  84 => ['en' => ['Sun-dried beef couscous', 'Couscous', 'Sun-dried beef', '1 plate 200 g'], 'es' => ['Cuscús de carne seca', 'Cuscús', 'Carne seca', '1 plato 200 g']],
  85 => ['en' => ['Chicken couscous', 'Couscous', 'Chicken', '1 plate 200 g'], 'es' => ['Cuscús de pollo', 'Cuscús', 'Pollo', '1 plato 200 g']],
  86 => ['en' => ['Ground beef couscous', 'Couscous', 'Ground beef', '1 plate 200 g'], 'es' => ['Cuscús de carne molida', 'Cuscús', 'Carne molida', '1 plato 200 g']],
  87 => ['en' => ['Milk couscous', 'Couscous', 'Milk', '1 plate with milk'], 'es' => ['Cuscús de leche', 'Cuscús', 'Leche', '1 plato con leche']],
  88 => ['en' => ['Coconut milk couscous', 'Couscous', 'Coconut milk', '1 plate with coconut milk'], 'es' => ['Cuscús de leche de coco', 'Cuscús', 'Leche de coco', '1 plato con leche de coco']],
  89 => ['en' => ['Sausage & cheese couscous', 'Couscous', 'Sausage & cheese', '1 plate 250 g'], 'es' => ['Cuscús de chorizo y queso', 'Cuscús', 'Chorizo y queso', '1 plato 250 g']],
  90 => ['en' => ['Bacon couscous', 'Couscous', 'Bacon', '1 plate 200 g'], 'es' => ['Cuscús de tocino', 'Cuscús', 'Tocino', '1 plato 200 g']],
  91 => ['en' => ['Tuna couscous', 'Couscous', 'Tuna', '1 plate 200 g'], 'es' => ['Cuscús de atún', 'Cuscús', 'Atún', '1 plato 200 g']],
  92 => ['en' => ['Hot dog sausage couscous', 'Couscous', 'Hot dog sausage', '1 plate 200 g'], 'es' => ['Cuscús de salchicha', 'Cuscús', 'Salchicha', '1 plato 200 g']],
  93 => ['en' => ['Stuffed couscous', 'Couscous', 'Stuffed', '1 stuffed slice 200 g'], 'es' => ['Cuscús de relleno', 'Cuscús', 'Relleno', '1 rebanada rellena 200 g']],
  94 => ['en' => ['Tapioca couscous', 'Couscous', 'Tapioca', '1 slice'], 'es' => ['Cuscús de tapioca', 'Cuscús', 'Tapioca', '1 rebanada']],
  95 => ['en' => ['São Paulo style couscous', 'Couscous', 'São Paulo style', '1 slice'], 'es' => ['Cuscús de estilo paulista', 'Cuscús', 'Estilo paulista', '1 rebanada']],
  40 => ['en' => ['Coconut beiju', null, 'Coconut beiju', '1 piece'], 'es' => ['Beiju de coco', null, 'Beiju de coco', '1 unidad']],
  41 => ['en' => ['Cake · Roll cake', 'Cake', 'Roll cake', '1 slice'], 'es' => ['Bizcocho de brazo gitano', 'Bizcocho', 'Brazo gitano', '1 rebanada']],
  42 => ['en' => ['Cake · Cassava', 'Cake', 'Cassava', '1 slice'], 'es' => ['Bizcocho de yuca', 'Bizcocho', 'Yuca', '1 rebanada']],
  43 => ['en' => ['Coconut candy', null, 'Coconut candy', '1 piece'], 'es' => ['Cocada', null, 'Cocada', '1 unidad']],
  44 => ['en' => ['Peanut brittle', null, 'Peanut brittle', '1 piece'], 'es' => ['Crocante de maní', null, 'Crocante de maní', '1 unidad']],
  45 => ['en' => ['Cartola (banana & cheese)', null, 'Cartola (banana & cheese)', '1 portion'], 'es' => ['Cartola (plátano y queso)', null, 'Cartola (plátano y queso)', '1 porción']],
  46 => ['en' => ['Sweet corn pudding', null, 'Sweet corn pudding', '1 bowl'], 'es' => ['Mazamorra', null, 'Mazamorra', '1 tazón']],
  47 => ['en' => ['Pamonha (corn tamale)', null, 'Pamonha (corn tamale)', '1 piece'], 'es' => ['Humita', null, 'Humita', '1 unidad']],
  48 => ['en' => ['Hominy pudding', null, 'Hominy pudding', '1 bowl'], 'es' => ['Mazamorra de maíz', null, 'Mazamorra de maíz', '1 tazón']],
  49 => ['en' => ['Grilled cheese skewer', null, 'Grilled cheese skewer', '1 skewer'], 'es' => ['Queso asado', null, 'Queso asado', '1 brocheta']],
  50 => ['en' => ['Cassava fries', null, 'Cassava fries', '1 portion'], 'es' => ['Yuca frita', null, 'Yuca frita', '1 porción']],
  51 => ['en' => ['Rice & beans (baião)', null, 'Rice & beans (baião)', '1 plate'], 'es' => ['Arroz con frijoles', null, 'Arroz con frijoles', '1 plato']],
  52 => ['en' => ['Sun-dried beef & cassava', null, 'Sun-dried beef & cassava', '1 plate'], 'es' => ['Carne seca con yuca', null, 'Carne seca con yuca', '1 plato']],
  53 => ['en' => ['Vatapá', null, 'Vatapá', '1 portion'], 'es' => ['Vatapá', null, 'Vatapá', '1 porción']],
  54 => ['en' => ['Sugarcane juice', null, 'Sugarcane juice', '1 glass 300 ml'], 'es' => ['Jugo de caña', null, 'Jugo de caña', '1 vaso 300 ml']],
  55 => ['en' => ['Coconut toffee', null, 'Coconut toffee', '1 piece'], 'es' => ['Turrón de coco', null, 'Turrón de coco', '1 trozo']],
  56 => ['en' => ['Raw cane sugar', null, 'Raw cane sugar', '1 piece 25 g'], 'es' => ['Panela', null, 'Panela', '1 trozo 25 g']],
  57 => ['en' => ['Tapioca fritters', null, 'Tapioca fritters', '3 pieces'], 'es' => ['Buñuelos de tapioca', null, 'Buñuelos de tapioca', '3 unidades']],
  204 => ['en' => ['Donut', null, 'Donut', '1 piece'], 'es' => ['Dona', null, 'Dona', '1 unidad']],
  205 => ['en' => ['Bagel', null, 'Bagel', '1 piece'], 'es' => ['Bagel', null, 'Bagel', '1 unidad']],
  206 => ['en' => ['Hot dog', null, 'Hot dog', '1 sandwich'], 'es' => ['Perrito caliente', null, 'Perrito caliente', '1 sándwich']],
  207 => ['en' => ['Taco', null, 'Taco', '1 taco'], 'es' => ['Taco', null, 'Taco', '1 taco']],
  208 => ['en' => ['Churros', null, 'Churros', '2 pieces'], 'es' => ['Churros', null, 'Churros', '2 unidades']],
  209 => ['en' => ['Empanada', null, 'Empanada', '1 piece'], 'es' => ['Empanada', null, 'Empanada', '1 unidad']],
  /* 1.17.0: cervejas, salgadinhos e chocolates de marca */
  236 => ['en' => ['Skol can', 'Beer', 'Skol can', 'can 350 ml'], 'es' => ['Skol lata', 'Cerveza', 'Skol lata', 'lata 350 ml']],
  237 => ['en' => ['Brahma Chopp can', 'Beer', 'Brahma Chopp can', 'can 350 ml'], 'es' => ['Brahma Chopp lata', 'Cerveza', 'Brahma Chopp lata', 'lata 350 ml']],
  238 => ['en' => ['Brahma 0.0 can', 'Beer', 'Brahma 0.0 can', 'can 350 ml'], 'es' => ['Brahma 0.0 lata', 'Cerveza', 'Brahma 0.0 lata', 'lata 350 ml']],
  239 => ['en' => ['Antarctica Pilsen can', 'Beer', 'Antarctica Pilsen can', 'can 350 ml'], 'es' => ['Antarctica Pilsen lata', 'Cerveza', 'Antarctica Pilsen lata', 'lata 350 ml']],
  240 => ['en' => ['Original can', 'Beer', 'Original can', 'can 350 ml'], 'es' => ['Original lata', 'Cerveza', 'Original lata', 'lata 350 ml']],
  241 => ['en' => ['Bohemia can', 'Beer', 'Bohemia can', 'can 350 ml'], 'es' => ['Bohemia lata', 'Cerveza', 'Bohemia lata', 'lata 350 ml']],
  242 => ['en' => ['Heineken can', 'Beer', 'Heineken can', 'can 350 ml'], 'es' => ['Heineken lata', 'Cerveza', 'Heineken lata', 'lata 350 ml']],
  243 => ['en' => ['Heineken 0.0 can', 'Beer', 'Heineken 0.0 can', 'can 350 ml'], 'es' => ['Heineken 0.0 lata', 'Cerveza', 'Heineken 0.0 lata', 'lata 350 ml']],
  244 => ['en' => ['Budweiser can', 'Beer', 'Budweiser can', 'can 350 ml'], 'es' => ['Budweiser lata', 'Cerveza', 'Budweiser lata', 'lata 350 ml']],
  245 => ['en' => ['Budweiser Zero can', 'Beer', 'Budweiser Zero can', 'can 350 ml'], 'es' => ['Budweiser Zero lata', 'Cerveza', 'Budweiser Zero lata', 'lata 350 ml']],
  246 => ['en' => ['Stella Artois long neck', 'Beer', 'Stella Artois long neck', 'long neck 330 ml'], 'es' => ['Stella Artois long neck', 'Cerveza', 'Stella Artois long neck', 'botella 330 ml']],
  247 => ['en' => ['Stella Artois 0.0 long neck', 'Beer', 'Stella Artois 0.0 long neck', 'long neck 330 ml'], 'es' => ['Stella Artois 0.0 long neck', 'Cerveza', 'Stella Artois 0.0 long neck', 'botella 330 ml']],
  248 => ['en' => ['Corona long neck', 'Beer', 'Corona long neck', 'long neck 330 ml'], 'es' => ['Corona long neck', 'Cerveza', 'Corona long neck', 'botella 330 ml']],
  249 => ['en' => ['Corona Cero long neck', 'Beer', 'Corona Cero long neck', 'long neck 330 ml'], 'es' => ['Corona Cero long neck', 'Cerveza', 'Corona Cero long neck', 'botella 330 ml']],
  250 => ['en' => ['Amstel can', 'Beer', 'Amstel can', 'can 350 ml'], 'es' => ['Amstel lata', 'Cerveza', 'Amstel lata', 'lata 350 ml']],
  251 => ['en' => ['Spaten can', 'Beer', 'Spaten can', 'can 350 ml'], 'es' => ['Spaten lata', 'Cerveza', 'Spaten lata', 'lata 350 ml']],
  252 => ['en' => ['Michelob Ultra long neck', 'Beer', 'Michelob Ultra long neck', 'long neck 330 ml'], 'es' => ['Michelob Ultra long neck', 'Cerveza', 'Michelob Ultra long neck', 'botella 330 ml']],
  253 => ['en' => ['Eisenbahn Pilsen can', 'Beer', 'Eisenbahn Pilsen can', 'can 350 ml'], 'es' => ['Eisenbahn Pilsen lata', 'Cerveza', 'Eisenbahn Pilsen lata', 'lata 350 ml']],
  254 => ['en' => ['Devassa can', 'Beer', 'Devassa can', 'can 350 ml'], 'es' => ['Devassa lata', 'Cerveza', 'Devassa lata', 'lata 350 ml']],
  255 => ['en' => ['Itaipava can', 'Beer', 'Itaipava can', 'can 350 ml'], 'es' => ['Itaipava lata', 'Cerveza', 'Itaipava lata', 'lata 350 ml']],
  256 => ['en' => ['Crystal can', 'Beer', 'Crystal can', 'can 350 ml'], 'es' => ['Crystal lata', 'Cerveza', 'Crystal lata', 'lata 350 ml']],
  257 => ['en' => ['Petra can', 'Beer', 'Petra can', 'can 350 ml'], 'es' => ['Petra lata', 'Cerveza', 'Petra lata', 'lata 350 ml']],
  258 => ['en' => ['Império can', 'Beer', 'Império can', 'can 350 ml'], 'es' => ['Império lata', 'Cerveza', 'Império lata', 'lata 350 ml']],
  259 => ['en' => ['Kaiser can', 'Beer', 'Kaiser can', 'can 350 ml'], 'es' => ['Kaiser lata', 'Cerveza', 'Kaiser lata', 'lata 350 ml']],
  260 => ['en' => ['Schin can', 'Beer', 'Schin can', 'can 350 ml'], 'es' => ['Schin lata', 'Cerveza', 'Schin lata', 'lata 350 ml']],
  261 => ['en' => ['Fandangos', 'Snacks', 'Fandangos', 'bag 45 g'], 'es' => ['Fandangos', 'Snacks', 'Fandangos', 'bolsa 45 g']],
  262 => ['en' => ['Baconzitos', 'Snacks', 'Baconzitos', 'bag 45 g'], 'es' => ['Baconzitos', 'Snacks', 'Baconzitos', 'bolsa 45 g']],
  263 => ['en' => ['Lay\'s', 'Snacks', 'Lay\'s', 'bag 45 g'], 'es' => ['Lay\'s', 'Snacks', 'Lay\'s', 'bolsa 45 g']],
  264 => ['en' => ['Pringles', 'Snacks', 'Pringles', 'serving 30 g'], 'es' => ['Pringles', 'Snacks', 'Pringles', 'porción 30 g']],
  265 => ['en' => ['Stax', 'Snacks', 'Stax', 'serving 30 g'], 'es' => ['Stax', 'Snacks', 'Stax', 'porción 30 g']],
  266 => ['en' => ['Elma Chips Sensações', 'Snacks', 'Elma Chips Sensações', 'bag 45 g'], 'es' => ['Elma Chips Sensações', 'Snacks', 'Elma Chips Sensações', 'bolsa 45 g']],
  267 => ['en' => ['Torcida', 'Snacks', 'Torcida', 'bag 45 g'], 'es' => ['Torcida', 'Snacks', 'Torcida', 'bolsa 45 g']],
  268 => ['en' => ['Fofura', 'Snacks', 'Fofura', 'bag 45 g'], 'es' => ['Fofura', 'Snacks', 'Fofura', 'bolsa 45 g']],
  269 => ['en' => ['Pingo d\'Ouro', 'Snacks', 'Pingo d\'Ouro', 'bag 45 g'], 'es' => ['Pingo d\'Ouro', 'Snacks', 'Pingo d\'Ouro', 'bolsa 45 g']],
  270 => ['en' => ['Club Social', 'Snacks', 'Club Social', 'bag 26 g'], 'es' => ['Club Social', 'Snacks', 'Club Social', 'bolsa 26 g']],
  271 => ['en' => ['KitKat', 'Chocolate', 'KitKat', '1 bar 41.5 g'], 'es' => ['KitKat', 'Chocolate', 'KitKat', '1 barra 41,5 g']],
  272 => ['en' => ['Bis', 'Chocolate', 'Bis', '4 pieces 25 g'], 'es' => ['Bis', 'Chocolate', 'Bis', '4 unidades 25 g']],
  273 => ['en' => ['Diamante Negro', 'Chocolate', 'Diamante Negro', 'serving 25 g'], 'es' => ['Diamante Negro', 'Chocolate', 'Diamante Negro', 'porción 25 g']],
  274 => ['en' => ['Laka', 'Chocolate', 'Laka', 'serving 25 g'], 'es' => ['Laka', 'Chocolate', 'Laka', 'porción 25 g']],
  275 => ['en' => ['Lacta Milk', 'Chocolate', 'Lacta Milk', 'serving 25 g'], 'es' => ['Lacta con Leche', 'Chocolate', 'Lacta con Leche', 'porción 25 g']],
  276 => ['en' => ['Sonho de Valsa', 'Chocolate', 'Sonho de Valsa', '1 bonbon 21.5 g'], 'es' => ['Sonho de Valsa', 'Chocolate', 'Sonho de Valsa', '1 bombón 21,5 g']],
  277 => ['en' => ['Ouro Branco', 'Chocolate', 'Ouro Branco', '1 bonbon 21.5 g'], 'es' => ['Ouro Branco', 'Chocolate', 'Ouro Branco', '1 bombón 21,5 g']],
  278 => ['en' => ['Twix', 'Chocolate', 'Twix', '1 pack 40 g'], 'es' => ['Twix', 'Chocolate', 'Twix', '1 paquete 40 g']],
  279 => ['en' => ['Snickers', 'Chocolate', 'Snickers', '1 bar 42 g'], 'es' => ['Snickers', 'Chocolate', 'Snickers', '1 barra 42 g']],
  280 => ['en' => ['M&M\'s', 'Chocolate', 'M&M\'s', 'bag 45 g'], 'es' => ['M&M\'s', 'Chocolate', 'M&M\'s', 'bolsa 45 g']],
  281 => ['en' => ['Kinder Bueno', 'Chocolate', 'Kinder Bueno', '1 pack 43 g'], 'es' => ['Kinder Bueno', 'Chocolate', 'Kinder Bueno', '1 paquete 43 g']],
  282 => ['en' => ['Kinder Surprise', 'Chocolate', 'Kinder Surprise', '1 egg 20 g'], 'es' => ['Kinder Sorpresa', 'Chocolate', 'Kinder Sorpresa', '1 huevo 20 g']],
  283 => ['en' => ['Batom Garoto bar', 'Chocolate', 'Batom Garoto bar', '1 piece 16 g'], 'es' => ['Batom Garoto', 'Chocolate', 'Batom Garoto', '1 unidad 16 g']],
  284 => ['en' => ['Talento', 'Chocolate', 'Talento', 'serving 25 g'], 'es' => ['Talento', 'Chocolate', 'Talento', 'porción 25 g']],
  285 => ['en' => ['Serenata de Amor', 'Chocolate', 'Serenata de Amor', '1 bonbon 20 g'], 'es' => ['Serenata de Amor', 'Chocolate', 'Serenata de Amor', '1 bombón 20 g']],
  286 => ['en' => ['Prestígio', 'Chocolate', 'Prestígio', '1 bar 33 g'], 'es' => ['Prestígio', 'Chocolate', 'Prestígio', '1 barra 33 g']],
  287 => ['en' => ['Chokito', 'Chocolate', 'Chokito', '1 bar 32 g'], 'es' => ['Chokito', 'Chocolate', 'Chokito', '1 barra 32 g']],
  288 => ['en' => ['Suflair', 'Chocolate', 'Suflair', '1 bar 50 g'], 'es' => ['Suflair', 'Chocolate', 'Suflair', '1 barra 50 g']],
  289 => ['en' => ['Galak', 'Chocolate', 'Galak', 'serving 25 g'], 'es' => ['Galak', 'Chocolate', 'Galak', 'porción 25 g']],
  290 => ['en' => ['Milka', 'Chocolate', 'Milka', 'serving 25 g'], 'es' => ['Milka', 'Chocolate', 'Milka', 'porción 25 g']],
  291 => ['en' => ['Toblerone', 'Chocolate', 'Toblerone', 'serving 25 g'], 'es' => ['Toblerone', 'Chocolate', 'Toblerone', 'porción 25 g']],
  292 => ['en' => ['Hershey\'s milk chocolate', 'Chocolate', 'Hershey\'s milk chocolate', 'serving 25 g'], 'es' => ['Hershey\'s con leche', 'Chocolate', 'Hershey\'s con leche', 'porción 25 g']],
  293 => ['en' => ['Ferrero Rocher', 'Chocolate', 'Ferrero Rocher', '1 bonbon 12.5 g'], 'es' => ['Ferrero Rocher', 'Chocolate', 'Ferrero Rocher', '1 bombón 12,5 g']],
  294 => ['en' => ['Nutella', 'Chocolate', 'Nutella', '1 spoon 15 g'], 'es' => ['Nutella', 'Chocolate', 'Nutella', '1 cuchara 15 g']],
];
